import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-video-wrapper">
          <video autoPlay muted loop playsInline className="bg-video">
            <source src="/0_Space_Planets_1080x1080.mov" type="video/quicktime" />
            Your browser does not support the video tag.
          </video>

          <div className="app-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
